### PR TITLE
Modified jsonschema_extras behaviour

### PR DESCRIPTION
**Pull request by jaskirat8**
jsonschema_extras will merge values of similar keys to array of values

### CODE REVIEW

**Comment by jaskirat8** [comment]
@alecthomas Can you check if this one can be merged without conflicts ?

**Comment by alecthomas** [comment]
Perfect, thanks. Can you document this in the README please? Otherwise LGTM.

**Comment by jaskirat8** [comment]
@alecthomas I have modified the main example also Readme.md to represent this change in behavior.
(two entries of foo in example, becomes array, while single entry remain as it is ) 
Does that look good or I should explicitly explain this ?

**Comment by alecthomas** [comment]
Thanks!

**Pull request merged**
