### PR TITLE
fix: interface must not be restricted to object type

### PR DESCRIPTION
**Pull request by sguiheux**
This fix this problem:

With this in the Go structure, map[string]interface{} , we cannot use . string/integer/bool as value of the map because of type object.
Interface{} must be more open :)

### CODE REVIEW

**Comment by alecthomas** [comment]
I see what you're saying but I'm not sure this is the right fix. I think we want to support both. Also can you add a test illustrating your issue?

**Comment by sguiheux** [comment]
The test illustrating the issue is already in the test file
`Tags    map[string]interface{} `json:"tags,omitempty"``

=>

`
tags: {
 "key": "value"
} 
`
is not valid

**Comment by sguiheux** [comment]
Build ok, f*** end of line ;)

**Comment by sguiheux** [comment]
So you don’t want to merge it ?

**Comment by alecthomas** [comment]
This doesn't support object and scalar cases no?

**Comment by sguiheux** [comment]
it supports all because I remove the type, so you can put want you want

**Comment by c9s** [comment]
👍

**Comment by alecthomas** [comment]
Thanks!

**Pull request merged**
