### PR TITLE
Extras can merge values of similar key to array of values

### PR DESCRIPTION
**Pull request by jaskirat8**

### CODE REVIEW

**Comment by alecthomas** [comment]
Hi! Thanks for the PR, but it has conflicts.

**Comment by jaskirat8** [comment]
Hi, I resolved all the conflicts and that was due to my previous readme.md submission. There is no code conflicts. If you want i will resubmit only the code part from fresh fork.

**Comment by alecthomas** [comment]
GitHub still says there are conflicts :\

**Comment by jaskirat8** [comment]
Oh. Okay. Filling PR from fresh fork then.
Thanks

**Pull request closed without merging**
